version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://190.146.2.119:2345/grupo11
      DB_USER: grupo11_user
      DB_PASSWORD: G11!vX9#qT7$$Lm2@R8zP