spring.application.name=web

spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo11
spring.datasource.username=grupo11_user
spring.datasource.password=G11!vX9#qT7$Lm2@R8zP
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.data-locations=classpath:db/init.sql
spring.sql.init.mode=never

app.security.enabled=true
app.security.jwt.secret=${JWT_SECRET:cambiarEnProduccionClaveMuyLargaParaHS512AlgoritmoSeguro123456}
app.security.jwt.expiration-ms=86400000


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


logging.level.org.springframework.security=DEBUG


logging.level.com.proyecto.web=DEBUG


logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# ===============================
# CONFIGURACION CORREO
# ===============================

# En false no envia correos reales, solo imprime el link en los logs del backend.
app.mail.enabled=true

# Correo remitente
app.mail.from=luisylosbugs@gmail.com

# URL del frontend local
app.frontend.base-url=http://localhost:4200

# ===============================
# SMTP
# ===============================
# Cuando tengan correo real, llenan estos datos y cambian app.mail.enabled=true

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=luisylosbugs@gmail.com
spring.mail.password=rhkv dvla slro zinv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true