spring.application.name=web

spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo11
spring.datasource.username=grupo11_user
spring.datasource.password=G11!vX9#qT7$Lm2@R8zP

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.frontend.base-url=http://localhost:8080/auth

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luisylosbugs@gmail.com
spring.mail.password=lzgk qdgj qfws fvre
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true