spring.application.name=web

spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo11
spring.datasource.username=grupo11_user
spring.datasource.password=G11!vX9#qT7$Lm2@R8zP

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true