spring.application.name=web

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.data-locations=classpath:db/init.sql
spring.sql.init.mode=never

app.security.enabled=true
app.security.jwt.secret=${JWT_SECRET:cambiarEnProduccionClaveMuyLargaParaHS512AlgoritmoSeguro123456}
app.security.jwt.expiration-ms=86400000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.com.proyecto.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# ===============================
# CONFIGURACION CORREO
# ===============================

app.mail.enabled=${APP_MAIL_ENABLED:true}
app.mail.from=${APP_MAIL_FROM:luisylosbugs@gmail.com}
app.frontend.base-url=${APP_FRONTEND_BASE_URL:https://grupo11.inphotech.co/front}

# ===============================
# SMTP
# ===============================

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
