spring.datasource.url=jdbc:postgresql://localhost:5432/mibd_local
spring.datasource.username=postgres
spring.datasource.password=LA_QUE_PUSISTE_AL_INSTALAR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect