apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-web
  namespace: grupo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto-web
  template:
    metadata:
      labels:
        app: proyecto-web
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: proyecto-web
        image: ghcr.io/advsnts/proyecto_web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-pablito
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-pablito
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-pablito
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-pablito
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-pablito
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: proyecto-web
  namespace: grupo11
spec:
  selector:
    app: proyecto-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto-web
  namespace: grupo11
spec:
  ingressClassName: public
  rules:
  - host: grupo11.inphotech.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proyecto-web
            port:
              number: 8080