kubectl create secret docker-registry ghcr-secret \
  --docker-server=ghcr.io \
  --docker-username=advSNTS \
  --docker-password=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 \
  --docker-email=187468015+advSNTS@users.noreply.github.com -n grupo11